# Generated by Django 5.0.1 on 2024-01-24 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="page_transitions",
        ),
        migrations.AddField(
            model_name="visit",
            name="routes_on_original_site",
            field=models.TextField(default="/"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together={("user", "url", "name")},
        ),
    ]
