# Generated by Django 5.0.1 on 2024-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vpn", "0003_visit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="start_page",
            field=models.URLField(default="http://127.0.0.1:8000/"),
            preserve_default=False,
        ),
    ]
